apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: dockkunal/jenkins-pipeline:latest
          ports:
            - name: http1
              containerPort: 81
